### ISSUE TITLE
fqnd not supported for zabbix sender

### ISSUE THREAD

**Issue by sergiogiuffrida** [zarplata/zabbix-agent-extension-mysql#5]
send hostname instead fqdn

**Comment by tears-of-noobs** [comment]
@sergiogiuffrida Hi. Can you explain more completely your situation and what's not work? This extension doesn't send metrics through `zabbix_sender` because extension have own zabbix_sender protocol implementation and extension automatically obtain hostname from your server/container by GoLang function `os.Hostname()` so, for correct work you should ensure that hostname on "client" (where extension installed) side equal with hostname on "server" (Added host in Zabbix server) side.
